databases:
  - name: discussion_forum_production
    databaseName: discussion_forum_production
    user: discussion_forum
    plan: free

services:
  - type: web
    name: discussion-forum
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: discussion_forum_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: REDIS_URL
        sync: false
    plan: free
    healthCheckPath: /
    autoDeploy: true

  - type: redis
    name: discussion-forum-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction 